import * as React from "react"
import { addPropertyControls } from "framer"
import {
    C,
    FONT,
    MONO,
    Icon,
    relTime,
} from "https://framer.com/m/DashboardLib-1-xD05ae.js"
import {
    type Activity,
} from "https://framer.com/m/DashboardData-6dyjDj.js"

// ============ AGENT CHAT ============
//
// Conversational sub-view inside the AgentRunPanel. Lets the user ask the
// running/completed agent questions, refine scope, or trigger follow-up
// actions. Responses are faux-streamed word-by-word with templated copy
// keyed off the agent type and the run's target.

export type ChatMessage = {
    id: string
    role: "user" | "agent"
    text: string
    full?: string // when set + streaming, text reveals progressively up to full
    streaming?: boolean
}

const TYPING_SPEED_MS = 35 // per word

// Suggested prompts keyed by agent type. Each one is the user's verbatim
// utterance; the response is generated by `respondTo()` below.
const SUGGESTIONS: Record<string, string[]> = {
    "Controls Agent": [
        "Explain this finding",
        "What evidence am I missing?",
        "Re-test with manual override",
    ],
    "Evidence Agent": [
        "Show me the source files",
        "Re-pull from this source",
        "Why was this filtered out?",
    ],
    "Risk Agent": [
        "Why this score?",
        "Compare with last quarter",
        "Show me the methodology",
    ],
    "Questionnaire Agent": [
        "Why this answer?",
        "Cite the policy",
        "Show draft alternatives",
    ],
    "Policy Agent": [
        "Show diff vs current",
        "What requirements does this map to?",
        "Send for legal review",
    ],
    "Remediation Agent": [
        "Prioritize this differently",
        "Add ownership",
        "Estimate effort",
    ],
    "Director Agent": [
        "Show cross-agent dependencies",
        "Re-run with broader scope",
        "Summarize what each agent did",
    ],
}

function respondTo(activity: Activity, userText: string): string {
    const q = userText.toLowerCase()
    const target = activity.target
    const agent = activity.agent

    // Common · explanation
    if (
        q.includes("explain") ||
        q.includes("why") ||
        q.includes("walk me through")
    ) {
        if (agent === "Controls Agent") {
            return `I evaluated ${target} against the framework's stated criteria. Three signals weighed in: the most recent evidence pull (under 24h old), the test history (3 of last 5 runs passed), and the owner's last review acknowledgement. The output reflects current state · I can re-test with a different evidence set or scope window if you want.`
        }
        if (agent === "Risk Agent") {
            return `The score weights inherent risk (data sensitivity, system criticality) at 60% and residual risk (controls in place, monitoring) at 40%. For ${target} the inherent risk is high, but the existing controls knock the residual down meaningfully. Methodology source: ISO 31000 + your custom weights from Settings → Risk.`
        }
        if (agent === "Evidence Agent") {
            return `Evidence for ${target} came from your connected sources · highest-confidence match was an access review log dated 4 days ago, plus a configuration snapshot from yesterday. I filtered out 2 lower-confidence candidates · happy to lower the threshold if you want to see them.`
        }
        return `For ${target}, I followed the playbook configured in Settings → ${agent.replace(" Agent", "")}. Each step is auditable in the Run timeline tab. Ask about a specific step and I can dig deeper.`
    }

    if (q.includes("missing") || q.includes("evidence")) {
        return `For ${target}, the highest-impact missing piece is a quarterly access review attestation from the control owner. I also flagged a stale configuration record (last refreshed 47 days ago, policy says 30). Want me to ping the owner or trigger an Evidence Agent re-pull?`
    }

    if (q.includes("re-test") || q.includes("rerun") || q.includes("re-run")) {
        return `Queueing a fresh run on ${target} with the current scope. Estimated 45 seconds. I'll surface a toast when it completes · or you can watch the Run timeline tab if you switch back.`
    }

    if (q.includes("source") || q.includes("files")) {
        return `For ${target} I pulled 4 evidence artifacts: 1 access log (Okta), 1 IaC snapshot (GitHub), 1 policy excerpt (Notion), 1 ticket reference (Jira). All four were within the 30-day freshness window. Want me to surface direct links or trigger a re-pull from one of them?`
    }

    if (q.includes("scope") || q.includes("broader") || q.includes("narrow")) {
        return `Current scope: ${target}. Broader scope options I can switch to: parent framework section, owner's full portfolio, or all related controls in the same testing family (7 candidates). Which one?`
    }

    if (q.includes("score") || q.includes("methodology")) {
        return `${target}'s score: inherent 8.2 / residual 4.1. Inherent comes from CVSS base + sensitivity multiplier. Residual factors in monitoring coverage (Datadog, AWS GuardDuty), incident response readiness, and patch SLA adherence. Full methodology is in Settings → Risk → Scoring model.`
    }

    if (q.includes("compare") || q.includes("quarter") || q.includes("baseline")) {
        return `Vs Q3 baseline: ${target} dropped from a 6.4 to a 4.1 residual. Three contributing changes: new monitoring rule (Q3 wk10), updated incident response runbook (Q3 wk7), and one false-positive reclassification. Net trend across the framework is positive.`
    }

    if (q.includes("ownership") || q.includes("owner") || q.includes("assign")) {
        return `${target} is currently unowned at the action level. Likely candidates based on framework section: Engineering (3), Security Ops (2), GRC (1). Most active for similar items in the last 90 days: Engineering. Want me to assign?`
    }

    if (q.includes("effort") || q.includes("estimate") || q.includes("how long")) {
        return `For ${target}'s remediation, my estimate is M (4-8 hours of focused work + 2-3 day async review cycle). Comparable past items averaged 6.2h hands-on. I can break it into sub-tasks if you want to assign in parallel.`
    }

    if (q.includes("policy") || q.includes("requirement") || q.includes("map")) {
        return `${target} maps to: SOC 2 CC6.1 (logical access), ISO 27001 A.9.2, NIST CSF PR.AC-1. Policy section "Access management" in your library covers the intent · I can surface the exact paragraph or draft a tighter version if needed.`
    }

    if (q.includes("draft") || q.includes("alternative") || q.includes("answer")) {
        return `I'll generate two alternative drafts for ${target} keyed to different reviewer audiences (auditor-facing vs internal-engineering). Each will cite the same evidence; the framing differs. Give me ~20 seconds.`
    }

    if (q.includes("dependencies") || q.includes("cross-agent")) {
        return `For this run on ${target}: Evidence Agent fed me 4 artifacts; Risk Agent's prior score informed prioritization; my output will feed Remediation Agent if anything fails. Director Agent has the cross-graph if you want the visual.`
    }

    if (q.includes("summarize") || q.includes("recap") || q.includes("what did")) {
        return `Run summary: ${agent} ${activity.action} ${target}. Total elapsed ~${Math.max(1, Math.floor((Date.now() - activity.createdAt) / 1000))}s. Pulled from your usual sources. No deviations from the standard playbook. Output is captured in the Run timeline tab.`
    }

    // Fallback · acknowledging + redirect
    return `Got it. For ${target}, the most useful next step is usually one of: explain the reasoning, surface the evidence, or re-run with adjusted scope. Want me to do any of those?`
}

export function AgentChat({
    activity,
    messages,
    setMessages,
}: {
    activity: Activity
    messages: ChatMessage[]
    setMessages: (
        updater: (prev: ChatMessage[]) => ChatMessage[]
    ) => void
}) {
    const [draft, setDraft] = React.useState("")
    const scrollRef = React.useRef<HTMLDivElement | null>(null)
    const inputRef = React.useRef<HTMLInputElement | null>(null)

    // Seed the welcome message on first mount for this activity. Owner is the
    // parent · we only push if the thread is empty.
    React.useEffect(() => {
        if (messages.length === 0) {
            setMessages(() => [
                {
                    id: "welcome",
                    role: "agent",
                    text: `Hi · I'm the ${activity.agent} on this run. Ask me anything about ${activity.target}, or pick one of the suggestions below.`,
                },
            ])
        }
        setDraft("")
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [activity.id])

    // Auto-scroll to bottom on new messages or as text streams in.
    React.useEffect(() => {
        const el = scrollRef.current
        if (!el) return
        el.scrollTop = el.scrollHeight
    }, [messages])

    const send = (text: string) => {
        if (!text.trim()) return
        const userId = `msg-${Date.now()}-u`
        const agentId = `msg-${Date.now()}-a`
        const full = respondTo(activity, text)
        setMessages((prev) => [
            ...prev,
            { id: userId, role: "user", text: text.trim() },
            {
                id: agentId,
                role: "agent",
                text: "",
                full,
                streaming: true,
            },
        ])
        setDraft("")
        // Stream the response word-by-word.
        const words = full.split(" ")
        let i = 1
        const tick = () => {
            if (i > words.length) {
                setMessages((prev) =>
                    prev.map((m) =>
                        m.id === agentId
                            ? { ...m, streaming: false, text: full }
                            : m
                    )
                )
                return
            }
            const partial = words.slice(0, i).join(" ")
            setMessages((prev) =>
                prev.map((m) =>
                    m.id === agentId ? { ...m, text: partial } : m
                )
            )
            i++
            window.setTimeout(tick, TYPING_SPEED_MS)
        }
        window.setTimeout(tick, 320)
    }

    const suggestions = SUGGESTIONS[activity.agent] ?? [
        "Explain what you did",
        "What's next?",
    ]
    const showSuggestions = messages.length <= 1

    return (
        <div
            style={{
                flex: 1,
                display: "flex",
                flexDirection: "column",
                minHeight: 0,
                background: C.surface,
            }}
        >
            <div
                ref={scrollRef}
                style={{
                    flex: 1,
                    overflowY: "auto",
                    padding: "18px 22px 14px 22px",
                    display: "flex",
                    flexDirection: "column",
                    gap: 12,
                }}
            >
                {messages.map((m) => (
                    <Bubble key={m.id} m={m} agentName={activity.agent} />
                ))}
                {showSuggestions && (
                    <div style={{ marginTop: 4 }}>
                        <div
                            style={{
                                font: `500 10px/14px ${FONT}`,
                                color: C.textSubtle,
                                textTransform: "uppercase",
                                letterSpacing: 0.4,
                                marginBottom: 8,
                            }}
                        >
                            Suggested
                        </div>
                        <div
                            style={{
                                display: "flex",
                                flexWrap: "wrap",
                                gap: 6,
                            }}
                        >
                            {suggestions.map((s) => (
                                <button
                                    key={s}
                                    type="button"
                                    onClick={() => send(s)}
                                    className="zbtn"
                                    style={{
                                        padding: "6px 10px",
                                        background: C.surfaceHi,
                                        border: `1px solid ${C.border}`,
                                        borderRadius: 999,
                                        cursor: "pointer",
                                        font: `500 12px/16px ${FONT}`,
                                        color: C.textMuted,
                                    }}
                                >
                                    {s}
                                </button>
                            ))}
                        </div>
                    </div>
                )}
            </div>

            <form
                onSubmit={(e) => {
                    e.preventDefault()
                    send(draft)
                }}
                style={{
                    padding: "12px 16px 14px 16px",
                    borderTop: `1px solid ${C.border}`,
                    background: "rgba(0,0,0,0.10)",
                    display: "flex",
                    alignItems: "center",
                    gap: 8,
                    flexShrink: 0,
                }}
            >
                <input
                    ref={inputRef}
                    value={draft}
                    onChange={(e) => setDraft(e.target.value)}
                    placeholder={`Ask the ${activity.agent}…`}
                    style={{
                        flex: 1,
                        padding: "9px 12px",
                        background: C.surfaceHi,
                        border: `1px solid ${C.border}`,
                        borderRadius: 8,
                        color: C.text,
                        font: `400 13px/18px ${FONT}`,
                        outline: "none",
                    }}
                />
                <button
                    type="submit"
                    className="zbtn"
                    disabled={!draft.trim()}
                    style={{
                        width: 36,
                        height: 36,
                        borderRadius: 8,
                        background: draft.trim() ? C.accent : C.surfaceHi,
                        border: "none",
                        cursor: draft.trim() ? "pointer" : "default",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        flexShrink: 0,
                    }}
                    aria-label="Send message"
                >
                    <Icon
                        n="arrowRight"
                        s={14}
                        c={draft.trim() ? "#FFFFFF" : C.textSubtle}
                    />
                </button>
            </form>
        </div>
    )
}

function Bubble({
    m,
    agentName,
}: {
    m: ChatMessage
    agentName: string
}) {
    const isUser = m.role === "user"
    return (
        <div
            style={{
                display: "flex",
                flexDirection: "column",
                alignItems: isUser ? "flex-end" : "flex-start",
                gap: 4,
                maxWidth: "100%",
            }}
        >
            {!isUser && (
                <div
                    style={{
                        font: `500 10px/14px ${FONT}`,
                        color: C.textSubtle,
                        textTransform: "uppercase",
                        letterSpacing: 0.4,
                        paddingLeft: 2,
                    }}
                >
                    {agentName}
                </div>
            )}
            <div
                style={{
                    maxWidth: "88%",
                    padding: "10px 12px",
                    borderRadius: 12,
                    background: isUser ? C.accent : C.surfaceHi,
                    border: isUser
                        ? `1px solid ${C.accent}`
                        : `1px solid ${C.border}`,
                    color: isUser ? "#FFFFFF" : C.text,
                    font: `400 13px/19px ${FONT}`,
                    whiteSpace: "pre-wrap",
                    wordBreak: "break-word",
                }}
            >
                {m.text}
                {m.streaming && (
                    <span
                        className="zcaret"
                        style={{
                            display: "inline-block",
                            width: 6,
                            marginLeft: 2,
                            color: isUser ? "#FFFFFF" : C.accentSoft,
                            font: `500 13px/19px ${MONO}`,
                        }}
                    >
                        ▎
                    </span>
                )}
            </div>
        </div>
    )
}

export default function AgentChatDefault() {
    return null
}

addPropertyControls(AgentChatDefault, {})
